from .add_keyboard_button import add_keyboard_button_callback
from .delete_keyboard_buttons import delete_keyboard_buttons_callback
from .delete_keyboard_button import delete_keyboard_button_callback
from .auth import auth_callback
