from .main_admin_keyboard import generate_main_admin_keyboard
from .text_back_keyboard import generate_text_back_keyboard
from .main_group_keyboard import generate_main_group_keyboard
from .group_buttons_types_keyboard import generate_group_buttons_types_keyboard
from .group_buttons_types_delete_keyboard import generate_group_buttons_types_delete_keyboard
from .auth_keyboard import generate_auth_keyboard
